# Distributions for key variables { .unnumbered}

## Distributions for key variables

A primary component of constraining $R(t)$ is how distributions are used to constrain key variables in $R(t)$ estimation: for $I(t)$, $ω$, and for $R(t)$ itself. 

Assuming some prior distributions for $R(t)$ and the generation interval permit an analytical solution for the posterior distribution of $R(t)$, as in [EpiEstim](package_EpiEstim.qmd). These simplifying assumptions greatly constrain the space of possible $R(t)$ values and thus calculation times are relatively fast. 

Other software packages, such as [EpiNow2](package_EpiNow2.qmd), have more flexibility at the cost of somewhat higher computational runtime and resources.

## Distributions used to define new offspring from cases

Another primary component of constraining $R(t)$ is how distributions are used to define the next generation of infections, or $I(t)$ as a function $I(t-i)$, for $0{\leq}i<t$. 

The renewal equation provides a mechanism for estimating the next batch of infectees that occur due to transmission from the current round of infectors, a branching process. The $I(t)$ calculated in the renewal equation represents the expected value of a discrete distribution. To account for stochasticity in estimating $R(t)$, we must specify this distribution.

The **Poisson distribution**, in which the mean and variance parameter $λ(t)=I(t)$, is used to represent the probability that a given number of events (i.e. infections) occur within a given time interval (i.e. one day), assuming that these events are independent. This is the simplest option to represent variation in infections. However, infections are often not independent, but can occur in clusters, e.g. in supersreading events. If this is an important factor in the spread of the infection, it is better to use a **Negative Binomial distribution**, with a mean parameter equal to $I(t)$ and a fitted size paramter to account for the "over-dispersion" of infections.


