# Inference frameworks { .unnumbered}

This page describes the different software / mathematical implementations of the solving the smoothing equations described previously.

## Bayesian optimization

*Section in progress*

```{r, include=FALSE, echo=F}
#  Assumes a distribution --> solved analytically
# •	EpiEstim
# o	restricted set of GI options (gamma?) enables analytical solve for the posterior estimate of R(t) which is also a Gamma, using conjugate priors
# 
# 	Doesn't assume a distribution of R(t) or I(t) --> Uses MCMC
# •	EpiNow2, implemented in STAN
# •	Hierarchical NUTS
```

## MaxLiklihood optimization

*Section in progress*

```{r, include=FALSE, echo=F}
# •	Frequentist
# o	RtEstim
# 
# Wallinga, J., and P. Teunis. "Different Epidemic Curves for Severe Acute Respiratory Syndrome Reveal Similar Impacts of Control Measures." American Journal of Epidemiology 160,no. 6 (2004): 509.
# •	^ this has the likelihood calculation in it
# 
# One of the most widely used methods for estimating time-varying reproduction number is a maximum likelihood-based approach {White, 2008}. 
# •	White LF, Pagano M. A likelihood-based method for real-time estimation of the serial interval and reproductive number of an epidemic. Stat Med 2008; 27(16): 2999–3016.
```


