# EpiFusion {#sec-top .unnumbered}


### Brief description

The paper by Judge et al. (2024) introduces EpiFusion, a novel method that integrates phylodynamic (genomic) and epidemiological (case incidence) data to jointly estimate the effective reproduction number (Rt) using particle filtering within a particle Markov Chain Monte Carlo (pMCMC) framework. The key goal of EpiFusion is to address limitations in Rt estimation when relying solely on epidemiological or genomic data—especially in poorly sampled epidemics such as arboviral and respiratory virus outbreaks.

EpiFusion leverages the complementary strengths of both data types to improve accuracy and certainty in real-time and retrospective outbreak analyses. The method is validated through simulation studies, benchmarking against existing tools (EpiNow2, BDSky, TimTam), and real-world application to the 2014 Ebola outbreak in Sierra Leone.

| [EpiFusion](package_EpiFusion.qmd#sec-top) | @Judge2024EpiFusion | [🔗](https://github.com/ciarajudge/EpiFusion) | Nov 30, 2024|

### Methods

This package contains the following methods:

- 

### Assessment

```{=html}
<table>
    <caption>Assessment rubric</caption>
    <!---HEADING --->
    <tr style="border-top: none;">
      <th style="font-weight: bold; width: 40%">Category</th>
      <th style="font-weight: bold; width: 40%">Notes</th>
      <th style="font-weight: bold; width: 20%">Scales</th>
    </tr>
    
        <!------ SECTION 1: USAGE -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Usage </td>
    </tr>

    <tr>
        <td>Runtime length</td>
        <td>Some description</td>
        <td>
          Time (minutes)
        </td>
    </tr>
      
      <!------ SECTION 2: FEATURES -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Features </td>
    </tr>
        <tr>
        <td>Ability to nowcast/forecast</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
                  </td>
    </tr>
                    <tr>
        <td>Incorporates delay distributions</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>
    
                        <tr>
        <td>Estimates expected cases </td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>

                        <tr>
        <td>Communicates uncertainty</td>
        <td>Some description</td>
        <td>
☐ Yes/no
        </td>
    </tr>

      <!------ SECTION 3: Validation -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Validation </td>
    </tr>
    
                        <tr>
        <td>Peer reviewed validation</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>
    
                        <tr>
        <td>Replicable documentation</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>


</table>

```



### Sample code
