# RtEstim { .unnumbered}

| | 
|:---|:--------|
| REF| @Liu2024rtestim|
| Docs| [https://dajmcdon.github.io/rtestim/](https://dajmcdon.github.io/rtestim/)|
| Github|  |
| Last commit| |
| Installation | [via devtools](https://dajmcdon.github.io/rtestim/)|
: {tbl-colwidths="[20,80]"}

### Brief description

Rtestim is a method that uses the renewal equation and a provided serial interval distribution to estimate $R_t$. Distinct from other methods, it uses a frequentist approach with an L1 smoothing penalty which decreases computation time and allows for locally adaptive estimates. The method estimates confidence bands for $R_t$ and incidence.

| [RtEstim](package_RtEstim.qmd) |  | [🔗](https://github.com/dajmcdon/rtestim) | Sep 25, 2024|

### Methods

This package contains the following methods:

- Locally adaptive estimator using Poisson trend filtering
- L1 smoothing
- Cross validation to select tuning parameters for the smoother

This approach is similar to [filtering](methods_time.qmd#sec-filtering)

### Assessment

| | 
|:---|:--------|
|<strong>Features</strong>||
| Ability to nowcast/forecast| No|
| Incorporates delay distributions| No|
| Estimates expected cases| Predicts based on estimated $R_t$|
| Communicates uncertainty| Yes|
|<strong>Validation</strong>||
| Documentation of package methods| Yes|
| Documentation of package implementation| Yes|
: {tbl-colwidths="[40,60]"}

### Sample code

The package website has [this helpful vignette](https://dajmcdon.github.io/rtestim/articles/rtestim.html).
