# ern { .unnumbered}

| | 
|:---|:--------|
| REF| @Champredon2024ern|
| Docs| |
| Github| [github.com/phac-nml-phrsd/ern](https://github.com/phac-nml-phrsd/ern) |
| Last commit|May 22, 2024 |
| Installation | [via devtools](https://github.com/phac-nml-phrsd/ern)|
: {tbl-colwidths="[20,80]"}

### Brief description

The [ern](package_ern.qmd) package was developed to adapt the [EpiEstim](package_EpiEstim.qmd) package for real world data, including wastewater and clinical data. Specifically the package:

-   disaggregates clinical reports into a shorter time unit to enable estimation of $R_t$ using an intrinsic generation interval on a useful timescale;
-   provides a framework to estimate $R_t$ from wastewater data, consistent with an estimation based on clinical data;
-   provides a user-friendly interface geared at public-health practitioners that may have limited proficiency in the R programming language;
-   uses EpiEstim for efficient and rapid estimation.

### Methods

This package combines the following methods:

- [fixed sliding windows](methods_time.qmd#sec-fixedwindow)

including an additional module for [disaggregation of data into shorter time units](methods_time.qmd#sec-disagg)

### Assessment

| | 
|:---|:--------|
|<strong>Features</strong>||
| Ability to nowcast/forecast| No |
| Incorporates delay distributions| Includes incubation period and reporting delay for clinical data |
| Estimates expected cases| Doing this from wastewater or aggregated clincal case data |
| Communicates uncertainty| Uncertainty from both EpiEstim approach, as well as assumptions made in estimating incident cases through resampling approach |
|<strong>Validation</strong>||
| Documentation of package methods| Yes|
| Documentation of package implementation| Yes |
: {tbl-colwidths="[40,60]"}

### Sample code

There is a [vignette](https://cran.r-project.org/web/packages/ern/vignettes/est-rt.html) and sample code and worked examples in the Plos One publication for this method @Champredon2024ern.
