# EstimateR { .unnumbered}

| | 
|:---|:--------|
| REF| @Scire2023estimateR|
| Docs| [covid-19-re.github.io/estimateR/index.html](https://covid-19-re.github.io/estimateR/index.html)|
| Github| [https://github.com/covid-19-Re/estimateR](https://github.com/covid-19-Re/estimateR) |
| Last commit| Sep 10, 2024|
| Installation | [via devtools](https://github.com/covid-19-Re/estimateR)|
: {tbl-colwidths="[20,80]"}

### Brief description

EstimateR is a package that is built on the EpiEstim framework for estimating $R_t$ and includes steps to smooth, backcalculate data to infection dates and create confidence intervals for estimates. Specifically, the method takes observed observations of infection events, such as case confirmations, hospital admissions, intensive care unit admissions, or deaths and performs the following four steps:

-   Smooth the data to reduce noise in the data.
-   Backcalculate data to date of infection.
-   Estimate $R_t$ using EpiEstim.
-   Calculate 95% confidence intervals using bootstrapping.

Each of these tasks can be done separately and the users is not required to perform all tasks.

There is apparently an option to nowcast data described and implemented in the package, though provided mathematical details are limited.


### Methods

This package contains the following methods:

-   Data is smoothed using LOESS with a first order polynomial. Users should adapt the smoothing parameter consistent with the noise in the input data.
-   Deconvolution with an Expectation-Maximization (EM) algorithm is used to create an estimate of the time series of infection events.
-   EpiEstim is used to estimate $R_t$ with a Bayesian framework, which uses [fixed sliding windows](methods_time.qmd#sec-fixedwindow).
-   Block bootstrapping is used to estimate 95% confidence intervals.

Details of the methods used are provided in the supplement of @Scire2023estimateR

### Assessment

| | 
|:---|:--------|
|<strong>Features</strong>||
| Ability to nowcast/forecast| Nowcasting, but details are limited |
| Incorporates delay distributions| Includes incubation period and reporting delay for clinical data |
| Estimates expected cases| Doing this from wastewater or aggregated clincal case data |
| Communicates uncertainty| Uncertainty from both EpiEstim approach, as well as assumptions made in estimating incident cases through resampling approach |
|<strong>Validation</strong>||
| Documentation of package methods| Yes|
| Documentation of package implementation| Yes |
: {tbl-colwidths="[40,60]"}

### Sample code

See [here](https://covid-19-re.github.io/estimateR/articles/incidence_data_workflow_example.html) for an example of calculating R(t) from aggregated incidence data, as well as other examples. 
