# epinowcast { .unnumbered}

| | 
|:---|:--------|
| REF| @lison2024generative|
| Docs| [epinowcast.org/](https://www.epinowcast.org/)|
| Github| [github.com/epinowcast](https://github.com/epinowcast/epinowcast) |
| Last commit| Sep 30, 2024|
| Installation | CRAN |
: {tbl-colwidths="[20,80]"}

### Description

::: {style="font-size:0.8em"}
Copied from the developer site<br><br>
:::

Tools to enable flexible and efficient hierarchical nowcasting of right-truncated epidemiological time-series using a semi-mechanistic Bayesian model with support for a range of reporting and generative processes. Nowcasting, in this context, is gaining situational awareness using currently available observations and the reporting patterns of historical observations. This can be useful when tracking the spread of infectious disease in real-time: without nowcasting, changes in trends can be obfuscated by partial reporting or their detection may be delayed due to the use of simpler methods like truncation. While the package has been designed with epidemiological applications in mind, it could be applied to any set of right-truncated time-series count data.

### Methods

This package contains the following methods:

-   [random walk](#sec-randomwalk)

### Assessment

| | 
|:---|:--------|
|<strong>Features</strong>||
| Ability to nowcast/forecast| Nowcasting |
| Incorporates delay distributions| Yes |
| Estimates expected cases| Yes |
| Communicates uncertainty| Yes |
|<strong>Validation</strong>||
| Documentation of package methods| Yes|
| Documentation of package implementation| Yes |
: {tbl-colwidths="[40,60]"}

### Sample code

A list of helpful vignettes are given [here](https://package.epinowcast.org/articles/).
