# R0 { .unnumbered}

| | 
|:---|:--------|
| REF| @obadia2012r0 |
| Docs| None |
| Github| [https://github.com/tobadia/R0](https://github.com/tobadia/R0) |
| Last commit| Feb, 2025 |
| Installation | [CRAN](https://cran.r-project.org/web/packages/R0/index.html)|
: {tbl-colwidths="[20,80]"}

### Brief description

A package that implements existing methods to estimate $R_0$ and $R_t$. The advantage of this package is that it standardizes data formats and the parameterization of the generation interval.

This package was developed in 2012 before many of the current methods were developed and most of the methods that are described in the package are not commonly used.


### Methods

This package contains the following methods:

- Function to define the generation interval. Options include empiric (i.e. multinomial), lognormal, gamma, and weibull distributions.
- Estimation of $R_0$ as a function of the attack rate (user must provide this).
- Method to estimate $R_0$ from the exponential growth rate described by [`Wallinga and Lipsitch`](https://pubmed.ncbi.nlm.nih.gov/17476782/).
- Maximum likelihood based estimate of $R_0$ and serial interval introduced by [`White and Pagano`](https://pubmed.ncbi.nlm.nih.gov/18058829/).
- Sequential Bayesian method to estimate time-varying reproductive number introduced by [`Bettencourt and Ribiero`](https://pubmed.ncbi.nlm.nih.gov/18478118/).
- Retrospective estimation of the time-varying reproductive number introduced by [`Wallinga and Teunis`](https://pubmed.ncbi.nlm.nih.gov/15353409/).

### Assessment

| | 
|:---|:--------|
|<strong>Features</strong>||
| Ability to nowcast/forecast| No |
| Incorporates delay distributions| No |
| Estimates expected cases| No |
| Communicates uncertainty| Some methods allow for this |
|<strong>Validation</strong>||
| Documentation of package methods| Yes|
| Documentation of package implementation| No |
: {tbl-colwidths="[40,60]"}

### Sample code

No vignettes are given, [this script](https://github.com/tobadia/R0/blob/master/demo/epid.demo.R) gives a very simple example, as does the [tests](https://github.com/tobadia/R0/tree/master/tests) folder.

